# Generated by Django 5.1.1 on 2025-05-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_is_jntuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='spl_dis',
            field=models.IntegerField(default=2),
        ),
    ]
